//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tamircisepeti22.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adre
    {
        public int Adresid { get; set; }
        public string aadres { get; set; }
        public int acity { get; set; }
        public int atown { get; set; }
        public int adistrict { get; set; }
        public Nullable<int> asellerid { get; set; }
        public Nullable<int> auid { get; set; }
    
        public virtual Ilceler Ilceler { get; set; }
        public virtual Iller Iller { get; set; }
        public virtual Seller Seller { get; set; }
        public virtual tCity_District_Street_Town tCity_District_Street_Town { get; set; }
        public virtual user user { get; set; }
    }
}
