//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tamircisepeti22.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hizmetler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hizmetler()
        {
            this.sepets = new HashSet<sepet>();
        }
    
        public int hizmetid { get; set; }
        public int hizmetfiyati { get; set; }
        public string hizmetadi { get; set; }
        public int sellerid { get; set; }
    
        public virtual Seller Seller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sepet> sepets { get; set; }
    }
}
