//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tamircisepeti22.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TmrsepetiEntities : DbContext
    {
        public TmrsepetiEntities()
            : base("name=TmrsepetiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adre> Adres { get; set; }
        public virtual DbSet<Authority> Authorities { get; set; }
        public virtual DbSet<hizmetler> hizmetlers { get; set; }
        public virtual DbSet<Ilceler> Ilcelers { get; set; }
        public virtual DbSet<Iller> Illers { get; set; }
        public virtual DbSet<Seller> Sellers { get; set; }
        public virtual DbSet<sepet> sepets { get; set; }
        public virtual DbSet<siparisler> siparislers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tCity_District_Street_Town> tCity_District_Street_Town { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
