//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tamircisepeti22.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siparisler
    {
        public int siparisid { get; set; }
        public int sellerid { get; set; }
        public int userid { get; set; }
        public int sepetid { get; set; }
        public bool yolda { get; set; }
        public bool onaylandı { get; set; }
    
        public virtual Seller Seller { get; set; }
        public virtual sepet sepet { get; set; }
        public virtual user user { get; set; }
    }
}
